/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GameStateDto } from "~tetris/dto/game-state-dto";
export namespace Components {
    interface AppRoot {
    }
    interface GameField {
        "state": GameStateDto;
    }
    interface GameLevel {
        "level": number;
    }
    interface GameScore {
        "score": number;
    }
    interface GameWrapper {
        "level": number;
        "nextItem": GameStateDto;
        "score": number;
        "state": GameStateDto;
    }
    interface LoginView {
    }
    interface PlayingView {
    }
    interface SuspendView {
    }
    interface WatchingView {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLGameFieldElement extends Components.GameField, HTMLStencilElement {
    }
    var HTMLGameFieldElement: {
        prototype: HTMLGameFieldElement;
        new (): HTMLGameFieldElement;
    };
    interface HTMLGameLevelElement extends Components.GameLevel, HTMLStencilElement {
    }
    var HTMLGameLevelElement: {
        prototype: HTMLGameLevelElement;
        new (): HTMLGameLevelElement;
    };
    interface HTMLGameScoreElement extends Components.GameScore, HTMLStencilElement {
    }
    var HTMLGameScoreElement: {
        prototype: HTMLGameScoreElement;
        new (): HTMLGameScoreElement;
    };
    interface HTMLGameWrapperElement extends Components.GameWrapper, HTMLStencilElement {
    }
    var HTMLGameWrapperElement: {
        prototype: HTMLGameWrapperElement;
        new (): HTMLGameWrapperElement;
    };
    interface HTMLLoginViewElement extends Components.LoginView, HTMLStencilElement {
    }
    var HTMLLoginViewElement: {
        prototype: HTMLLoginViewElement;
        new (): HTMLLoginViewElement;
    };
    interface HTMLPlayingViewElement extends Components.PlayingView, HTMLStencilElement {
    }
    var HTMLPlayingViewElement: {
        prototype: HTMLPlayingViewElement;
        new (): HTMLPlayingViewElement;
    };
    interface HTMLSuspendViewElement extends Components.SuspendView, HTMLStencilElement {
    }
    var HTMLSuspendViewElement: {
        prototype: HTMLSuspendViewElement;
        new (): HTMLSuspendViewElement;
    };
    interface HTMLWatchingViewElement extends Components.WatchingView, HTMLStencilElement {
    }
    var HTMLWatchingViewElement: {
        prototype: HTMLWatchingViewElement;
        new (): HTMLWatchingViewElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "game-field": HTMLGameFieldElement;
        "game-level": HTMLGameLevelElement;
        "game-score": HTMLGameScoreElement;
        "game-wrapper": HTMLGameWrapperElement;
        "login-view": HTMLLoginViewElement;
        "playing-view": HTMLPlayingViewElement;
        "suspend-view": HTMLSuspendViewElement;
        "watching-view": HTMLWatchingViewElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface GameField {
        "state"?: GameStateDto;
    }
    interface GameLevel {
        "level"?: number;
    }
    interface GameScore {
        "score"?: number;
    }
    interface GameWrapper {
        "level"?: number;
        "nextItem"?: GameStateDto;
        "score"?: number;
        "state"?: GameStateDto;
    }
    interface LoginView {
    }
    interface PlayingView {
    }
    interface SuspendView {
    }
    interface WatchingView {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "game-field": GameField;
        "game-level": GameLevel;
        "game-score": GameScore;
        "game-wrapper": GameWrapper;
        "login-view": LoginView;
        "playing-view": PlayingView;
        "suspend-view": SuspendView;
        "watching-view": WatchingView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "game-field": LocalJSX.GameField & JSXBase.HTMLAttributes<HTMLGameFieldElement>;
            "game-level": LocalJSX.GameLevel & JSXBase.HTMLAttributes<HTMLGameLevelElement>;
            "game-score": LocalJSX.GameScore & JSXBase.HTMLAttributes<HTMLGameScoreElement>;
            "game-wrapper": LocalJSX.GameWrapper & JSXBase.HTMLAttributes<HTMLGameWrapperElement>;
            "login-view": LocalJSX.LoginView & JSXBase.HTMLAttributes<HTMLLoginViewElement>;
            "playing-view": LocalJSX.PlayingView & JSXBase.HTMLAttributes<HTMLPlayingViewElement>;
            "suspend-view": LocalJSX.SuspendView & JSXBase.HTMLAttributes<HTMLSuspendViewElement>;
            "watching-view": LocalJSX.WatchingView & JSXBase.HTMLAttributes<HTMLWatchingViewElement>;
        }
    }
}
