export const enum SocketEvent {
  RegisterUser = 'registerUser',
  UserLoginSuccess = 'userLoginSuccess',
  AddUser = 'AddUser',
  RemoveUser = 'RemoveUser',
  Disconnect = 'disconnect',
  ConnectSuccess = 'connect',
  ConnectFailed = 'connect_error',
  ReconnectSuccess = 'reconnect',
  ReconnectError = 'reconnect_error',
  ReconnectFailed = 'reconnect_failed',
  StartWatchingMode = 'StartWatchingMode',
  StopWatchingMode = 'StopWatchingMode',
  StartPlayingMode = 'StartPlayingMode',
  StopPlayingMode = 'StopPlayingMode',
  StartNewGame = 'StartNewGame',
  MoveFigure = 'MoveFigure',
  RotateFigure = 'RotateFigure',
  DropFigure = 'DropFigure',
  UpdateGameView = 'UpdateGameView',
  UpdateNextFigure = 'UpdateNextFigure',
  UpdateScore = 'UpdateScore',
  UpdateLevel = 'UpdateLevel',
}
